### ISSUE TITLE
incompatible restrict options for Solaris 10

### ISSUE THREAD

**Issue by Phil-Friderici** [ghoneycutt/puppet-module-ntp#60]
The module is using restrict options that are incompatible with Solaris 10. Because of that the complete line for restrict is ignored leading to an completly unrestricted NTP server.

Error messages show that the restrict lines are ignored (at all)
<pre>
Feb  5 15:49:21 sol10 xntpd[35808]: [ID 504011 daemon.error] getnetnum: "-4" invalid host number, line ignored
Feb  5 15:49:21 sol10 xntpd[35808]: [ID 504011 daemon.error] getnetnum: "-6" invalid host number, line ignored
Feb  5 15:49:21 sol10 xntpd[35808]: [ID 504011 daemon.error] getnetnum: "::1" invalid host number, line ignored
Feb  5 15:49:21 sol10 xntpd[35808]: [ID 269952 daemon.error] can't open key file /etc/inet/ntp.keys: No such file or directory
Feb  5 15:49:21 sol10 xntpd[35808]: [ID 241925 daemon.error] configure: keyword "tinker" unknown, line ignored
Feb  5 15:49:24 sol10 xntpd[35808]: [ID 373468 daemon.error] adj_frequency: ntp_adjtime failed: Not owner
</pre>

To restrict ntp on Solaris 10 these line would be sufficient:
<pre>
restrict default noserve noquery
restrict 127.0.0.1
</pre>

Should I create a PR with (new) valid defaults for Solaris 10 ?

**Comment by Phil-Friderici** [comment]
wanna see the PR first ?

**Comment by ghoneycutt** [comment]
Any PR's in this area are of course certainly welcomed. :)

I don't have testing ability on Solaris 10, so if you are seeing errors, let's get 'em fixed!

**Comment by Phil-Friderici** [comment]
@ghoneycutt thanks for merging :)
